### ISSUE TITLE
`acorn containers` should be able to provide information about computeclass 

### ISSUE THREAD

**Issue by sangee2004** [acorn-io/runtime#1293] opened 2023-03-01 03:13 UTC
acorn version v0.6.0-rc1-6-gb57d7f88+b57d7f88

It will be good to have `acorn containers` report information about the computeclass with which it was deployed.

**Comment by cjellick** [comment] 2023-11-15 14:33
closing as dupe of https://github.com/acorn-io/runtime/issues/1821

**Closed by cjellick** 2023-11-15 14:33 UTC
Labels: kind/enhancement
