### ISSUE TITLE
Nested Acorns -  delete and updates on stand alone apps fail 

### ISSUE THREAD

**Issue by sangee2004** [acorn-io/runtime#1690] opened 2023-06-02 01:51 UTC
acorn version v0.7.0-alpha1-129-g9238600a+9238600a

Steps to reproduce the problem:
Deploy nested acorns.
```
acorns: {
    "my-acorn1": {
        image: "ghcr.io/acorn-io/library/hello-world:latest"
    }
    "my-acorn2": {
        image: "docker.io/sangeetha/myfirstacorn:v0.0.1"
    }
}
```
```
acorn apps
NAME              IMAGE          HEALTHY   UP-TO-DATE   CREATED   ENDPOINTS                                                                         MESSAGE
test1             79ffabbb3e81   0         0            8s ago                                                                                      OK
test1.my-acorn1   1a6c64d2ccd0   1         1            8s ago    http://webapp-test1-my-acorn1-dcb52faa-9f078f1f.local.oss-acorn.io => webapp:80   OK
test1.my-acorn2   12e4e9a38517   1         1            8s ago    http://myweb1-test1-my-acorn2-d0a51b09-7fa1cefb.local.oss-acorn.io => myweb1:80   OK
```
Attempting to delete child apps , results in apps getting redeployed.
Not able to update individual apps. 
```
acorn update -l test1=value1 test1.my-acorn2
  ✗  ERROR:  App.api.acorn.io "test1.my-acorn2" is invalid: metadata.name: Invalid value: "test1.my-acorn2": a DNS-1035 label must consist of lower case alphanumeric characters or '-', start with an alphabetic character, and end with an alphanumeric character (e.g. 'my-name',  or 'abc-123', regex used for validation is '[a-z]([-a-z0-9]*[a-z0-9])?')
```

If the intent is for us to not allow for deleting/updating the child app independently in the nested acorn, we should be able to not attempt these actions and provide user with a proper error message.

**Comment by g-linville** [comment] 2023-06-05 15:26
@cjellick @ibuildthecloud do we want to support directly updating and deleting nested acorns like this?

**Comment by cjellick** [comment] 2023-06-05 18:35
I think this issue, https://github.com/acorn-io/acorn/issues/1596, and https://github.com/acorn-io/acorn/issues/1600 need the same fundamental question answered: can a user update a nested acorn app or service (ie one with a dot in the name because it was launched by another acorn).

For now, I am saying we DO NOT want to support that. @ibuildthecloud may come in and override me, but that's the call i'm making for now.

**Comment by cjellick** [comment] 2023-06-26 16:49
Ok, confirmed with @ibuildthecloud and closing the loop on this.

You SHOULD be able to delete a nested app/service and the expected behavior is that it redeploys
You SHOULD NOT be able to update a nested acorn/service "except in a devsession"

I believe this is the current behavior for both, so moving this to QA.

**Comment by sangee2004** [comment] 2023-07-17 19:07
Tested with acorn version - `v0.8.0-alpha7-98-gbb130866+bb130866`

We now provide proper error message when attempting to update nested acorn apps.

```
 acorn update -l test1=value1 mytestnested.my-acorn2
  ✗  ERROR:  App.api.acorn.io "mytestnested.my-acorn2" is invalid: metadata.name: Invalid value: "mytestnested.my-acorn2": To update a nested Acorn or a service, update the parent Acorn instead.

```

**Comment by sangee2004** [comment] 2023-07-17 19:14
@g-linville Wanted conformation on this behavior w.r.t deploying nested acorn in devsession.

Deploy nested acorn in dev mode.
Attempting to update nested acorn app or the standalone app within the nested acorn fails.


```
 acorn update -l test1=value1 mytestnesteddev.my-acorn2
  ✗  ERROR:  App.api.acorn.io "mytestnesteddev.my-acorn2" is invalid: metadata.name: Invalid value: "mytestnesteddev.my-acorn2": To update a nested Acorn or a service, update the parent Acorn instead.
sangeethahariharan@Sangeethas-MacBook-Pro secretgetter % acorn update -l test1=value1 mytestnesteddev          
  ✗  ERROR:  App.api.acorn.io "mytestnesteddev" is invalid: status.devSession: Invalid value: "": app is locked by dev session
```

**Comment by cjellick** [comment] 2023-08-25 16:53
closing this. dont see what else we want to change here

**Closed by cjellick** 2023-08-25 16:53 UTC
Labels: kind/bug
