### ISSUE TITLE
Limit list of authorized characters in basic secret

### ISSUE THREAD

**Issue by lucj** [acorn-io/runtime#2192] opened 2023-09-29 08:38 UTC
Currently we can specify the characters we want to be used in a secret of type token, the example below is from the doc:

```
secret: {
    password: {
        type: "token"
        params: {
            length: 16
            characters: "abcdedfhifj01234567890"
        }
        data: token: ""
    }
}
```

That should be great to have the same behavior for secret of type basic as well. Basic secret are great to create database username/password on the fly but because the chars list does not prevent special chars it cannot be used to generate postgres username/password for instance.

I think that could be great if the chars restriction is available for basic secret as well.

**Comment by lucj** [comment] 2023-10-05 16:11
Just an additional note ;)
Could the list of characters be also represented with a-z, A-Z, 0-9 so we can use "a-zA-Z0-9" for aphanumerical characters ?

**Comment by njhale** [comment] 2023-10-15 16:22
Merged the change to parameterize basic auth secrets, will be adding the `"a-zA-Z0-9"` enhancement in a follow-up!

**Comment by sangee2004** [comment] 2023-10-15 20:53
Tested with acorn version - `v0.9.0-rc1-31-gbdd8d407+bdd8d407`

Able to limit list of authorized character for basic secret's username and password.

1. Deployed secrets with type `basic`:
```
secrets: {
    password: {
        type: "basic"
        params: {
            usernameLength: 16
            usernameCharacters: "abcdedfhifj01234567890"
            passwordLength: 16
            passwordCharacters: "abcdedfhifj01234567890"
        }
    }
}
```

This results in secrets being created with the provided size and character set for both username and password fields.
```
acorn secrets reveal testnew.password 
NAME               TYPE      KEY        VALUE
testnew.password   basic     password   0eb0fa93fehhf7e8
testnew.password   basic     username   04cadd2d5dd6fead
```

2. Another example with more restricted character set and different ones for username and password fields also work as expected.
```
secrets: {
    password: {
        type: "basic"
        params: {
            usernameLength: 10
            usernameCharacters: "xyz123"
            passwordLength: 7
            passwordCharacters: "atyu9"
        }
    }
}
```

```
acorn secret reveal testres.password  
NAME               TYPE      KEY        VALUE
testres.password   basic     password   a9tytyy
testres.password   basic     username   313z2323yz
```

**Comment by njhale** [comment] 2023-10-16 23:58
Just merged support for "character range" syntax sugar: #2250

**Comment by sangee2004** [comment] 2023-10-17 01:08
Tested with Acorn version - `v0.9.0-rc1-37-g2be8a309+2be8a309`

Able to restrict character set for username and password by specifying  value like -`A-Za-z0-9` and they work as expected.


@njhale When specifying format like `a-Z` or `Z-a` we only get secrets generated with `a` and `Z` . Wanted to confirm that this is as intended . I am able to get all alphabets (lower and upper case) when specifying `A-z` which is as expected.

**Comment by njhale** [comment] 2023-10-17 16:27
> When specifying format like a-Z or Z-a we only get secrets generated with a and Z . Wanted to confirm that this is as intended . I am able to get all alphabets (lower and upper case) when specifying A-z of z-A

yup -- looks like you ran into an edge-case that I didn't account for. Working on a fix now.

**Comment by njhale** [comment] 2023-10-17 17:11
Here's the fix: https://github.com/acorn-io/runtime/pull/2255

**Comment by njhale** [comment] 2023-10-18 01:10
For reference, that fix does the following:

> Treat mixed case and backwards ranges (e.g. A-z, 0-A, z-a) as
individual characters in the given set. This simplifies the UX and
makes ranges easier to reason about.

**Comment by sangee2004** [comment] 2023-10-18 01:47
Tested with acorn version - `v0.9.0-rc1-43-gbe8054c6+be8054c6`

Mixed case and backwards ranges are now considered as individual characters in the given set.

Using `z-A` , `Z-a`,`a-Z`,`A-z` for `usernameCharacters` and `passwordCharacters` when creating secrets results in individual characters in the given set as being allowed characters.
This is true for  backwards ranges for numbers as well like `9-0` , `6-3`.

**Closed by sangee2004** 2023-10-18 01:47 UTC

**Comment by sangee2004** [comment] 2023-10-19 22:59
a-z,A-Z, 0-9 syntax is not yet implemented for the token type secrets.

**Comment by lucj** [comment] 2023-10-20 13:03
Hi, 
I have created the following secret:
```
secrets: {
    user: {
        type: "basic"
        params: {
            usernameLength: 7
            usernameCharacters: "a-z"
            passwordLength: 10
            passwordCharacters: "a-Z0-9"
        }
        data: {  
            username: ""
            password: ""
        }
    }
}
```
Looking at the generated password, I get the following:
```
$ acorn secret reveal mgo.user mgo.admin
NAME        TYPE      KEY        VALUE
mgo.user    basic     password   6Z4670Z-94
mgo.user    basic     username   pobaahs
```
On another secret I got this content: "a524278-48"
Is there anything I'm doing wrong ?

**Comment by sangee2004** [comment] 2023-10-20 16:34
@lucj `a-Z` will only translate to "a", "-","Z" since this range has mixed case which is not supported. Instead of using "a-Z0-9" using "A-Za-z0-9" will result in all lower case/uppercase  alphabets and numbers.

**Comment by lucj** [comment] 2023-10-20 16:44
My bad I misread the above comment. Thanks @sangee2004
