### ISSUE TITLE
Issues with `acorn update`

### ISSUE THREAD

**Issue by sangee2004** [acorn-io/runtime#1487] opened 2023-04-13 17:58 UTC
acorn version v0.6.0-158-g3b6f3c99+3b6f3c99

Following are the list of issues seen with `acorn update`

#### Issue 1: Not able to pass directories to `acorn update`

Steps to Reproduce:
1. Deploy App - app1 from current dir -  `acorn run -n mytestnew .`
2. Make changes to Acornfile.
3. `acorn update mytestnew . `

Result:
```
acorn update mytestnew . 
mytestnew
┌──────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
| STATUS: ENDPOINTS[http://myweb1-mytestnew-63389b74.local.on-acorn.io => myweb1:80] HEALTHY[1] UPTODATE[1] OK |
└──────────────────────────────────────────────────────────────────────────────────────────────────────────────┘

┌──────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
| STATUS: ENDPOINTS[http://myweb1-mytestnew-63389b74.local.on-acorn.io => myweb1:80] HEALTHY[1] UPTODATE[1] OK |
└──────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
```
Changes  from Acornfile doesnot get applied after update.

Note - `acorn update -f Acornfile mytestnew` works. But we will need this to work for a directory as well. 

#### Issue 2: Acorn update should not create new apps when non existent app names are provided to it.

Steps to reproduce:
1. Run acorn update using an app name that doesn't exist:
```
acorn update -f Acornfile <newapp name>
or
acorn update --image <image> <newapp name>
```

This results in a new app being created. I'd expect it return a validation error saying an app of that name doesn't exist.

**Comment by cjellick** [comment] 2023-05-02 20:14
@ibuildthecloud did another round of refactor on run and update. He said these commands are now where he wants them to be. 

Give  them a test @sangee2004 and report back any new issues.

**Comment by sangee2004** [comment] 2023-05-03 00:46
Tested with `acorn version v0.7.0-alpha1-30-gf1f1abfe+f1f1abfe`

Issues mentioned in the bug are still happening.

**Comment by cjellick** [comment] 2023-05-31 16:01
I might bump this one out. Need to try it out one more time

**Comment by g-linville** [comment] 2023-06-27 21:20
For the first of these two cases, I would argue that this is the expected behavior.

For `acorn run`, the only argument is the image. But for `acorn update`, the only argument is the app name. So if you do `acorn run -n myapp .` and then want to apply the changes from the Acornfile later on, the command would be `acorn update --image . myapp`.

**Comment by g-linville** [comment] 2023-06-27 21:28
Additionally, the code right now very intentionally allows apps to be created with `acorn update` if the app name specified does not exist. This is not a bug; it was intentional. I can change this if we want, but I would like to get confirmation on that first.

**Comment by cjellick** [comment] 2023-06-29 19:35
Discussed in standup and determined that both of these are behaving as intended. @g-linville will just add a clarifying point to the `acorn udpate --help`.

Grant, just do that and then you can self-close this issue

**Closed** 2023-06-30 14:24 UTC
Labels: kind/bug
